In [43]:
#Import

import pandas as pd
import numpy as np
import re
import gc
import sys
import math
from datetime import date

In [44]:
#Mounting the drive to ensure data can be uploaded from Google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [45]:
#Main Path

path_main_attitudes = '/content/drive/MyDrive/Alpha_beta_gamma/Coding/Data Prep/Attitudes/'

attitudes_labels = pd.read_csv(path_main_attitudes + "Attitudes_labels.csv")
#attitudes.drop('Unnamed: 0', inplace=True, axis=1)

attitudes = pd.read_csv(path_main_attitudes + "Attitudes.csv")

In [46]:
attitudes

,R0000100,R0010300,R0010310,R0010400,R0010410,R0010500,R0013100,R0013200,R0015900,R0016000,...,T8162900,T8162901,T8162902,T8162903,T8162904,T8162905,T8162906,T8162907,T8162908,T8162909
0,1,7,7,7,7,5,3,3,-4,-4,...,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5
1,2,7,7,7,7,5,3,3,-4,-4,...,-4,-4,-4,-4,-4,-4,-4,-4,-4,-4
2,3,7,7,7,7,2,3,4,-4,-4,...,-4,-4,-4,-4,-4,-4,-4,-4,-4,-4
3,4,7,7,7,7,1,3,3,2,3,...,-4,-4,-4,-4,-4,-4,-4,-4,-4,-4
4,5,7,7,7,7,1,3,3,-4,-4,...,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12681,12682,7,7,7,7,4,4,4,-4,-4,...,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5
12682,12683,2,2,2,2,1,2,3,-4,-4,...,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5
12683,12684,7,7,0,0,2,2,1,-4,-4,...,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5
12684,12685,2,2,9,219,4,2,2,-4,-4,...,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5
12685,12686,0,0,1,1,6,2,2,-4,-4,...,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5

In [47]:
attitudes_labels

,RNUM,QUESTION NAME,VARIABLE TITLE,YEAR,Type,var_name
0,T0961700,IMPATIENCE_1,AMOUNT OF $ RESPONDENT WOULD WAIT 1 MONTH TO R...,2006,ctn,ctn_IMPATIENCE_1__2006
1,T0962000,IMPATIENCE_2,AMOUNT OF $ RESPONDENT WOULD WAIT 1 YEAR TO RE...,2006,ctn,ctn_IMPATIENCE_2__2006
2,R0149200,OTHER-3A,ATTITUDE OF INFLUENTIAL PERSON TO R'S DECISION...,1979,cat_o,cat_o_OTHER-3A__1979
3,R0149400,OTHER-3C,ATTITUDE OF INFLUENTIAL PERSON TO R'S DECISION...,1979,cat_o,cat_o_OTHER-3C__1979
4,R0149500,OTHER-3D,ATTITUDE OF INFLUENTIAL PERSON TO R'S DECISION...,1979,cat_o,cat_o_OTHER-3D__1979
...,...,...,...,...,...,...
328,T0279100,RISK-INCOME-1,WOULD R TAKE JOB THAT COULD EITHER DOUBLE FAMI...,2006,cat_d,cat_d_RISK-INCOME-1__2006
329,R4395900,RISK-INCOME-2,WOULD R TAKE JOB THAT COULD EITHER DOUBLE FAMI...,1993,cat_d,cat_d_RISK-INCOME-2__1993
330,R7353400,RISK-INCOME-2,WOULD R TAKE JOB THAT COULD EITHER DOUBLE FAMI...,2002,cat_d,cat_d_RISK-INCOME-2__2002
331,R8047200,RISK-INCOME-2,WOULD R TAKE JOB THAT COULD EITHER DOUBLE FAMI...,2004,cat_d,cat_d_RISK-INCOME-2__2004
332,T0279200,RISK-INCOME-2,WOULD R TAKE JOB THAT COULD EITHER DOUBLE FAMI...,2006,cat_d,cat_d_RISK-INCOME-2__2006

In [48]:
attitudes = attitudes.rename(columns={"R0000100": "ID", "R0173600": "SAMPLE_ID", "R0214700":"SAMPLE_RACE" , "R0214800":"SAMPLE_SEX"})

In [49]:
rnum_list = attitudes_labels["RNUM"].values.tolist()
new_var_name = attitudes_labels["var_name"].values.tolist()

for i in range(0,len(rnum_list)):
  attitudes = attitudes.rename(columns={rnum_list[i]:new_var_name[i]})

In [50]:
print(sorted(attitudes.columns.tolist()))
attitudes

['ID', 'SAMPLE_ID', 'SAMPLE_RACE', 'SAMPLE_SEX', 'cat_ATT-POL-77__2008', 'cat_ATT-POL-78A__2008', 'cat_ATT-POL-78__2008', 'cat_ESP-2B_1__1982', 'cat_ESP-2B__1982', 'cat_EXP-10B__1979', 'cat_EXP-1A__1979', 'cat_EXP-1A__1982', 'cat_EXP-1__1979', 'cat_EXP-1__1980', 'cat_EXP-1__1981', 'cat_EXP-1__1982', 'cat_EXP-1__1983', 'cat_EXP-1__1984', 'cat_EXP-2A__1979', 'cat_EXP-2A__1982', 'cat_EXP-2B_1__1979', 'cat_EXP-2B__1979', 'cat_EXP-OCC_2__1979', 'cat_EXP-OCC_2__1982', 'cat_EXP-OCC__1979', 'cat_EXP-OCC__1982', 'cat_OTHER-2__1979', 'cat_R_REL-1_COL__1979', 'cat_R_REL-1__1979', 'cat_R_REL-1__2000', 'cat_R_REL-2_COL__1979', 'cat_R_REL-2__1979', 'cat_R_REL-2__1982', 'cat_R_REL-2__2000', 'cat_R_REL-2__2012', 'cat_R_REL-2__2014', 'cat_R_REL-2__2016', 'cat_R_REL-2__2018', 'cat_R_REL-4__1982', 'cat_R_REL-5__1982', 'cat_SP_REL-1__1982', 'cat_SP_REL-1__2000', 'cat_SP_REL-1__2002', 'cat_SP_REL-1__2004', 'cat_SP_REL-1__2006', 'cat_SP_REL-1__2008', 'cat_SP_REL-1__2010', 'cat_SP_REL-1__2012', 'cat_SP_REL-1__2014', 'cat_SP_REL-1__2016', 'cat_SP_REL-1__2018', 'cat_SP_REL-2_D__1982', 'cat_SP_REL-2__1982', 'cat_SP_REL-2__2000', 'cat_SP_REL-2__2002', 'cat_SP_REL-2__2004', 'cat_SP_REL-2__2006', 'cat_SP_REL-2__2008', 'cat_SP_REL-2__2010', 'cat_SP_REL-2__2012', 'cat_SP_REL-2__2014', 'cat_SP_REL-2__2016', 'cat_SP_REL-2__2018', 'cat_SP_REL-3_D__1982', 'cat_SP_REL-4_D__1982', 'cat_SP_REL-4__1982', 'cat_SP_REL-5_D__1982', 'cat_SP_REL-5__1982', 'cat_SP_REL-6_D__1982', 'cat_SP_REL-6__1982', 'cat_SP_REL-7_D__1982', 'cat_SP_REL-7__1982', 'cat_WOW-OCC__1979', 'cat_d_EXP-2__1979', 'cat_d_EXP-2__1980', 'cat_d_EXP-2__1981', 'cat_d_EXP-2__1982', 'cat_d_EXP-2__1983', 'cat_d_EXP-2__1984', 'cat_d_RISK-INCOME-1__1993', 'cat_d_RISK-INCOME-1__2002', 'cat_d_RISK-INCOME-1__2004', 'cat_d_RISK-INCOME-1__2006', 'cat_d_RISK-INCOME-1__2010', 'cat_d_RISK-INCOME-1__2012', 'cat_d_RISK-INCOME-1__2014', 'cat_d_RISK-INCOME-2__1993', 'cat_d_RISK-INCOME-2__2002', 'cat_d_RISK-INCOME-2__2004', 'cat_d_RISK-INCOME-2__2006', 'cat_d_RISK-INCOME-2__2010', 'cat_d_RISK-INCOME-2__2012', 'cat_d_RISK-INCOME-2__2014', 'cat_d_RISK-INCOME-3__1993', 'cat_d_RISK-INCOME-3__2002', 'cat_d_RISK-INCOME-3__2004', 'cat_d_RISK-INCOME-3__2006', 'cat_d_RISK-INCOME-3__2010', 'cat_d_RISK-INCOME-3__2012', 'cat_d_RISK-INCOME-3__2014', 'cat_d_RISK_LINT__2012', 'cat_d_RISK_LINT__2014', 'cat_d_ROTTER_1A__1979', 'cat_d_ROTTER_1A__2014', 'cat_d_ROTTER_1A__2016', 'cat_d_ROTTER_1A__2018', 'cat_d_ROTTER_1B__1979', 'cat_d_ROTTER_1B__2014', 'cat_d_ROTTER_1B__2016', 'cat_d_ROTTER_1B__2018', 'cat_d_ROTTER_2A__1979', 'cat_d_ROTTER_2A__2014', 'cat_d_ROTTER_2A__2016', 'cat_d_ROTTER_2A__2018', 'cat_d_ROTTER_2B__1979', 'cat_d_ROTTER_2B__2014', 'cat_d_ROTTER_2B__2016', 'cat_d_ROTTER_2B__2018', 'cat_d_ROTTER_3A__1979', 'cat_d_ROTTER_3A__2014', 'cat_d_ROTTER_3A__2016', 'cat_d_ROTTER_3A__2018', 'cat_d_ROTTER_3B__1979', 'cat_d_ROTTER_3B__2014', 'cat_d_ROTTER_3B__2016', 'cat_d_ROTTER_3B__2018', 'cat_d_ROTTER_4A__1979', 'cat_d_ROTTER_4A__2014', 'cat_d_ROTTER_4A__2016', 'cat_d_ROTTER_4A__2018', 'cat_d_ROTTER_4B__1979', 'cat_d_ROTTER_4B__2014', 'cat_d_ROTTER_4B__2016', 'cat_d_ROTTER_4B__2018', 'cat_d_WOW-4__1979', 'cat_o_ATT-POL-78C__2008', 'cat_o_ATT-POL-79__2008', 'cat_o_ATT-POL-80__2008', 'cat_o_ATT-POL-84__2008', 'cat_o_HEALTH-SOC_1__1985', 'cat_o_HEALTH-SOC_2__1985', 'cat_o_OTHER-3A__1979', 'cat_o_OTHER-3B__1979', 'cat_o_OTHER-3C__1979', 'cat_o_OTHER-3D__1979', 'cat_o_OTHER-3E__1979', 'cat_o_OTHER-3F__1979', 'cat_o_OTHER-3G__1979', 'cat_o_OTHER-3H__1979', 'cat_o_PEARLIN_1__1992', 'cat_o_PEARLIN_2__1992', 'cat_o_PEARLIN_3__1992', 'cat_o_PEARLIN_4__1992', 'cat_o_PEARLIN_5__1992', 'cat_o_PEARLIN_6__1992', 'cat_o_PEARLIN_7__1992', 'cat_o_Q10-69~000005__1988', 'cat_o_Q10-69~000005__1992', 'cat_o_Q10-69~000005__1994', 'cat_o_Q10-69~000005__1996', 'cat_o_Q10-69~000005__1998', 'cat_o_Q10-69~000005__2000', 'cat_o_Q10-69~000005__2002', 'cat_o_Q10-69~000005__2004', 'cat_o_Q10-69~000005__2006', 'cat_o_Q10-69~000005__2008', 'cat_o_Q10-69~000005__2010', 'cat_o_Q10-69~000005__2012', 'cat_o_Q10-69~000005__2014', 'cat_o_Q10-69~000005__2016', 'cat_o_RISK_4__2010', 'cat_o_RISK_4__2012', 'cat_o_RISK_4__2014', 'cat_o_RISK_5~000001__2010', 'cat_o_RISK_5~000001__2012', 'cat_o_RISK_5~000001__2014', 'cat_o_RISK_5~000002__2010', 'cat_o_RISK_5~000002__2012', 'cat_o_RISK_5~000002__2014', 'cat_o_RISK_5~000003__2010', 'cat_o_RISK_5~000003__2012', 'cat_o_RISK_5~000003__2014', 'cat_o_RISK_5~000004__2010', 'cat_o_RISK_5~000004__2012', 'cat_o_RISK_5~000004__2014', 'cat_o_RISK_5~000005__2010', 'cat_o_RISK_5~000005__2012', 'cat_o_RISK_5~000005__2014', 'cat_o_RISK_5~000006__2010', 'cat_o_RISK_5~000006__2012', 'cat_o_RISK_5~000006__2014', 'cat_o_RISK_5~000007__2010', 'cat_o_RISK_5~000007__2012', 'cat_o_RISK_5~000007__2014', 'cat_o_ROSENBERG_ESTEEM~000001__1980', 'cat_o_ROSENBERG_ESTEEM~000001__1987', 'cat_o_ROSENBERG_ESTEEM~000002__1980', 'cat_o_ROSENBERG_ESTEEM~000002__1987', 'cat_o_ROSENBERG_ESTEEM~000003__1980', 'cat_o_ROSENBERG_ESTEEM~000003__1987', 'cat_o_ROSENBERG_ESTEEM~000004__1980', 'cat_o_ROSENBERG_ESTEEM~000004__1987', 'cat_o_ROSENBERG_ESTEEM~000005__1980', 'cat_o_ROSENBERG_ESTEEM~000005__1987', 'cat_o_ROSENBERG_ESTEEM~000006__1980', 'cat_o_ROSENBERG_ESTEEM~000006__1987', 'cat_o_ROSENBERG_ESTEEM~000007__1980', 'cat_o_ROSENBERG_ESTEEM~000007__1987', 'cat_o_ROSENBERG_ESTEEM~000008__1980', 'cat_o_ROSENBERG_ESTEEM~000008__1987', 'cat_o_ROSENBERG_ESTEEM~000009__1980', 'cat_o_ROSENBERG_ESTEEM~000009__1987', 'cat_o_ROSENBERG_ESTEEM~000010__1980', 'cat_o_ROSENBERG_ESTEEM~000010__1987', 'cat_o_R_REL-3__1979', 'cat_o_R_REL-3__1982', 'cat_o_R_REL-3__2000', 'cat_o_R_REL-3__2012', 'cat_o_R_REL-3__2014', 'cat_o_R_REL-3__2016', 'cat_o_R_REL-3__2018', 'cat_o_SCHOOL-3A_1__1979', 'cat_o_SCHOOL-3A_2__1979', 'cat_o_SCHOOL-3A_3__1979', 'cat_o_SCHOOL-3A_4__1979', 'cat_o_SCHOOL-3A_5__1979', 'cat_o_SCHOOL-3A_6__1979', 'cat_o_SCHOOL-3A_7__1979', 'cat_o_SCHOOL-3A_8__1979', 'cat_o_SCHOOL-3A_9__1979', 'cat_o_SCHOOL-3B__1979', 'cat_o_SP_REL-3__1982', 'cat_o_SP_REL-3__2000', 'cat_o_SP_REL-3__2002', 'cat_o_SP_REL-3__2004', 'cat_o_SP_REL-3__2006', 'cat_o_SP_REL-3__2008', 'cat_o_SP_REL-3__2010', 'cat_o_SP_REL-3__2012', 'cat_o_SP_REL-3__2014', 'cat_o_SP_REL-3__2016', 'cat_o_SP_REL-3__2018', 'cat_o_TIPI10~000001__2014', 'cat_o_TIPI10~000001__2016', 'cat_o_TIPI10~000001__2018', 'cat_o_TIPI10~000002__2014', 'cat_o_TIPI10~000002__2016', 'cat_o_TIPI10~000002__2018', 'cat_o_TIPI10~000003__2014', 'cat_o_TIPI10~000003__2016', 'cat_o_TIPI10~000003__2018', 'cat_o_TIPI10~000004__2014', 'cat_o_TIPI10~000004__2016', 'cat_o_TIPI10~000004__2018', 'cat_o_TIPI10~000005__2014', 'cat_o_TIPI10~000005__2016', 'cat_o_TIPI10~000005__2018', 'cat_o_TIPI10~000006__2014', 'cat_o_TIPI10~000006__2016', 'cat_o_TIPI10~000006__2018', 'cat_o_TIPI10~000007__2014', 'cat_o_TIPI10~000007__2016', 'cat_o_TIPI10~000007__2018', 'cat_o_TIPI10~000008__2014', 'cat_o_TIPI10~000008__2016', 'cat_o_TIPI10~000008__2018', 'cat_o_TIPI10~000009__2014', 'cat_o_TIPI10~000009__2016', 'cat_o_TIPI10~000009__2018', 'cat_o_TIPI10~000010__2014', 'cat_o_TIPI10~000010__2016', 'cat_o_TIPI10~000010__2018', 'cat_o_WOMENS-ROLES_000001__1979', 'cat_o_WOMENS-ROLES_000001__1982', 'cat_o_WOMENS-ROLES_000001__1987', 'cat_o_WOMENS-ROLES_000002__1979', 'cat_o_WOMENS-ROLES_000002__1982', 'cat_o_WOMENS-ROLES_000002__1987', 'cat_o_WOMENS-ROLES_000003__1979', 'cat_o_WOMENS-ROLES_000003__1982', 'cat_o_WOMENS-ROLES_000003__1987', 'cat_o_WOMENS-ROLES_000004__1979', 'cat_o_WOMENS-ROLES_000004__1982', 'cat_o_WOMENS-ROLES_000004__1987', 'cat_o_WOMENS-ROLES_000005__1979', 'cat_o_WOMENS-ROLES_000005__1982', 'cat_o_WOMENS-ROLES_000005__1987', 'cat_o_WOMENS-ROLES_000006__1979', 'cat_o_WOMENS-ROLES_000006__1982', 'cat_o_WOMENS-ROLES_000006__1987', 'cat_o_WOMENS-ROLES_000007__1979', 'cat_o_WOMENS-ROLES_000007__1982', 'cat_o_WOMENS-ROLES_000007__1987', 'cat_o_WOMENS-ROLES_000008__1979', 'cat_o_WOMENS-ROLES_000008__1982', 'cat_o_WOMENS-ROLES_000008__1987', 'cat_o_WOMENS-ROLES~000001__2004', 'cat_o_WOMENS-ROLES~000002__2004', 'cat_o_WOMENS-ROLES~000003__2004', 'cat_o_WOMENS-ROLES~000004__2004', 'cat_o_WOMENS-ROLES~000005__2004', 'cat_o_WOMENS-ROLES~000006__2004', 'cat_o_WOMENS-ROLES~000007__2004', 'cat_o_WOMENS-ROLES~000008__2004', 'ctn_FER-1A__1979', 'ctn_FER-1A__1982', 'ctn_FER-1B__1979', 'ctn_FER-1B__1982', 'ctn_IMPATIENCE_1_SR000001__2006', 'ctn_IMPATIENCE_1_SR000002__2006', 'ctn_IMPATIENCE_1__2006', 'ctn_IMPATIENCE_2_SR000001__2006', 'ctn_IMPATIENCE_2_SR000002__2006', 'ctn_IMPATIENCE_2__2006', 'ctn_PEARLIN_SCORE__1992', 'ctn_RISK_1_SR000001__2006', 'ctn_RISK_1_SR000002__2006', 'ctn_RISK_1__2006', 'ctn_RISK_2_SR000001__2006', 'ctn_RISK_2_SR000002__2006', 'ctn_RISK_2__2006', 'ctn_RISK_3_SR000001__2006', 'ctn_RISK_3_SR000002__2006', 'ctn_RISK_3__2006', 'ctn_RISK_4_SR000001__2006', 'ctn_RISK_4_SR000002__2006', 'ctn_RISK_4__2006', 'ctn_RISK_5H__2010', 'ctn_RISK_5H__2012', 'ctn_RISK_5H__2014', 'ctn_ROSENBERG_ESTEEM_SCORE__1980', 'ctn_ROSENBERG_ESTEEM_SCORE__1987', 'ctn_ROSENBERG_ESTEEM_SCORE__2006', 'ctn_ROTTER_SCORE__1979', 'ctn_ROTTER_SCORE__2014', 'ctn_ROTTER_SCORE__2016', 'ctn_ROTTER_SCORE__2018']

,ID,cat_R_REL-1_COL__1979,cat_R_REL-1__1979,cat_R_REL-2_COL__1979,cat_R_REL-2__1979,cat_o_R_REL-3__1979,ctn_FER-1A__1979,ctn_FER-1B__1979,cat_o_SCHOOL-3A_1__1979,cat_o_SCHOOL-3A_2__1979,...,cat_o_TIPI10~000001__2018,cat_o_TIPI10~000002__2018,cat_o_TIPI10~000003__2018,cat_o_TIPI10~000004__2018,cat_o_TIPI10~000005__2018,cat_o_TIPI10~000006__2018,cat_o_TIPI10~000007__2018,cat_o_TIPI10~000008__2018,cat_o_TIPI10~000009__2018,cat_o_TIPI10~000010__2018
0,1,7,7,7,7,5,3,3,-4,-4,...,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5
1,2,7,7,7,7,5,3,3,-4,-4,...,-4,-4,-4,-4,-4,-4,-4,-4,-4,-4
2,3,7,7,7,7,2,3,4,-4,-4,...,-4,-4,-4,-4,-4,-4,-4,-4,-4,-4
3,4,7,7,7,7,1,3,3,2,3,...,-4,-4,-4,-4,-4,-4,-4,-4,-4,-4
4,5,7,7,7,7,1,3,3,-4,-4,...,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12681,12682,7,7,7,7,4,4,4,-4,-4,...,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5
12682,12683,2,2,2,2,1,2,3,-4,-4,...,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5
12683,12684,7,7,0,0,2,2,1,-4,-4,...,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5
12684,12685,2,2,9,219,4,2,2,-4,-4,...,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5
12685,12686,0,0,1,1,6,2,2,-4,-4,...,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5

In [51]:
attitudes[attitudes < 0 ] = np.nan 
attitudes[attitudes > 20000 ] = np.nan 
attitudes

,ID,cat_R_REL-1_COL__1979,cat_R_REL-1__1979,cat_R_REL-2_COL__1979,cat_R_REL-2__1979,cat_o_R_REL-3__1979,ctn_FER-1A__1979,ctn_FER-1B__1979,cat_o_SCHOOL-3A_1__1979,cat_o_SCHOOL-3A_2__1979,...,cat_o_TIPI10~000001__2018,cat_o_TIPI10~000002__2018,cat_o_TIPI10~000003__2018,cat_o_TIPI10~000004__2018,cat_o_TIPI10~000005__2018,cat_o_TIPI10~000006__2018,cat_o_TIPI10~000007__2018,cat_o_TIPI10~000008__2018,cat_o_TIPI10~000009__2018,cat_o_TIPI10~000010__2018
0,1,7.0,7.0,7.0,7.0,5.0,3.0,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,7.0,7.0,7.0,7.0,5.0,3.0,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,7.0,7.0,7.0,7.0,2.0,3.0,4.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,7.0,7.0,7.0,7.0,1.0,3.0,3.0,2.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,7.0,7.0,7.0,7.0,1.0,3.0,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12681,12682,7.0,7.0,7.0,7.0,4.0,4.0,4.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12682,12683,2.0,2.0,2.0,2.0,1.0,2.0,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12683,12684,7.0,7.0,0.0,0.0,2.0,2.0,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12684,12685,2.0,2.0,9.0,219.0,4.0,2.0,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12685,12686,0.0,0.0,1.0,1.0,6.0,2.0,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
id_list = ["ID", "SAMPLE_ID", "SAMPLE_RACE" , "SAMPLE_SEX"]
new_var_name_unqiue = [ x[:-6] for x in new_var_name]
new_var_name_unqiue = list(set(new_var_name_unqiue))
new_var_name_unqiue.sort()

print(len(new_var_name_unqiue))

149

In [53]:
def remove_sparse_col(df, var_list, year_list, threshold):
  
  num_missing = 0 
  for i in var_list: num_missing = num_missing + df[i].isna().sum() 
  if num_missing > threshold * len(var_list):
    df = df.drop(columns=var_list)
  output = df
  return output



for i in new_var_name_unqiue:
  sub_var_name = [x for x in new_var_name if x[:-6] == i ]
  sub_year = [x[-4:] for x in sub_var_name ]
  attitudes = remove_sparse_col(attitudes, sub_var_name, sub_year, 5000)

In [54]:
# printing = attitudes.columns.tolist()
# printing.sort()
# printing

In [55]:
def add_year(df, var_name, ref_year ,begin_year, end_year):
  for i in range(begin_year, end_year+1):
    added_name = var_name + "__"+str(i)
    ref_name = var_name + "__"+ str(ref_year)
    df[added_name] = df[ref_name]
  output = df.copy()
  return output

def add_begining(df, var_name, ref_year):
  added_name = var_name + "__1979"
  ref_name = var_name + "__"+ ref_year
  df[added_name] = df[ref_name]
  return df.copy()

def add_multiple_ref_year(df, var_name, year_list):
  year_list.sort()
  if year_list[0]!= "1979": 
    df = add_begining(df, var_name, year_list[0])
    year_list.insert(0, "1979")
  for i in range(1,len(year_list)):
    df = add_year(df, var_name, year_list[i-1] , int(year_list[i-1]), int(year_list[i])-1)
    if i == len(year_list)-1:
      #From last element in the list to 2018
      df = add_year(df, var_name, year_list[i] , int(year_list[i]), 2018)

  output = df.copy()
  return output 


def expand_year(df, id_list):
  sub_var_list = [x[:-6] for x in df.columns.tolist() if x not in id_list]
  sub_var_list = list(set(sub_var_list))
  sub_var_list.sort()
  #sub_var_list = sub_var_list[0:10]            
  for i in sub_var_list: 
    sub_var_name = [x for x in df.columns.tolist() if x[:-6] == i ] 
    sub_year = [x[-4:] for x in sub_var_name]
    if len(sub_year) == 1:
      df = add_year(df, i , sub_year[0], 1979, 2018)
    else:
      df = add_multiple_ref_year(df, i , sub_year) 
  
  test_list  = [x for x in df.columns.tolist() if x[:-6] in sub_var_list]
  test_list.sort()
  print(len(test_list))



  output = df 
  #output = test_list
  return output 


attitudes = expand_year(attitudes, id_list)


#attitudes_test

1520

In [56]:
a = attitudes.columns.tolist()
a.sort()
sub_unique_var_name = [x[:-6] for x in a if x not in id_list]
sub_unique_var_name= list(set(sub_unique_var_name))

In [57]:
sub_unique_var_name

['cat_o_HEALTH-SOC_1',
 'cat_o_PEARLIN_3',
 'ctn_PEARLIN_SCORE',
 'cat_o_WOMENS-ROLES_000003',
 'cat_o_WOMENS-ROLES_000001',
 'ctn_FER-1B',
 'cat_o_PEARLIN_2',
 'cat_o_PEARLIN_6',
 'cat_o_PEARLIN_7',
 'cat_d_WOW-4',
 'cat_o_PEARLIN_5',
 'cat_o_ROSENBERG_ESTEEM~000001',
 'cat_o_ROSENBERG_ESTEEM~000003',
 'cat_o_WOMENS-ROLES_000008',
 'cat_o_ROSENBERG_ESTEEM~000009',
 'cat_o_HEALTH-SOC_2',
 'cat_o_PEARLIN_1',
 'ctn_ROSENBERG_ESTEEM_SCORE',
 'cat_R_REL-2_COL',
 'cat_o_WOMENS-ROLES_000002',
 'cat_o_ROSENBERG_ESTEEM~000004',
 'cat_o_WOMENS-ROLES_000005',
 'cat_o_WOMENS-ROLES_000004',
 'cat_o_WOMENS-ROLES_000006',
 'cat_o_ROSENBERG_ESTEEM~000008',
 'cat_EXP-1',
 'cat_o_PEARLIN_4',
 'cat_o_ROSENBERG_ESTEEM~000002',
 'cat_R_REL-1_COL',
 'cat_o_ROSENBERG_ESTEEM~000006',
 'cat_o_ATT-POL-79',
 'ctn_FER-1A',
 'cat_EXP-OCC',
 'cat_o_ROSENBERG_ESTEEM~000010',
 'cat_o_ROSENBERG_ESTEEM~000005',
 'cat_o_WOMENS-ROLES_000007',
 'cat_o_ROSENBERG_ESTEEM~000007',
 'cat_R_REL-1']

In [58]:
print(len(sub_unique_var_name))

38

In [59]:
for i in range(1979, 2019):
  c = [x for x in a if x[-4:]== str(i)]
  print(str(i) + " ->  " + str(len(c)))

1979 ->  38
1980 ->  38
1981 ->  38
1982 ->  38
1983 ->  38
1984 ->  38
1985 ->  38
1986 ->  38
1987 ->  38
1988 ->  38
1989 ->  38
1990 ->  38
1991 ->  38
1992 ->  38
1993 ->  38
1994 ->  38
1995 ->  38
1996 ->  38
1997 ->  38
1998 ->  38
1999 ->  38
2000 ->  38
2001 ->  38
2002 ->  38
2003 ->  38
2004 ->  38
2005 ->  38
2006 ->  38
2007 ->  38
2008 ->  38
2009 ->  38
2010 ->  38
2011 ->  38
2012 ->  38
2013 ->  38
2014 ->  38
2015 ->  38
2016 ->  38
2017 ->  38
2018 ->  38

In [60]:
attitudes

,ID,cat_R_REL-1_COL__1979,cat_R_REL-1__1979,cat_R_REL-2_COL__1979,ctn_FER-1A__1979,ctn_FER-1B__1979,cat_d_WOW-4__1979,cat_o_WOMENS-ROLES_000001__1979,cat_o_WOMENS-ROLES_000002__1979,cat_o_WOMENS-ROLES_000003__1979,...,ctn_ROSENBERG_ESTEEM_SCORE__2009,ctn_ROSENBERG_ESTEEM_SCORE__2010,ctn_ROSENBERG_ESTEEM_SCORE__2011,ctn_ROSENBERG_ESTEEM_SCORE__2012,ctn_ROSENBERG_ESTEEM_SCORE__2013,ctn_ROSENBERG_ESTEEM_SCORE__2014,ctn_ROSENBERG_ESTEEM_SCORE__2015,ctn_ROSENBERG_ESTEEM_SCORE__2016,ctn_ROSENBERG_ESTEEM_SCORE__2017,ctn_ROSENBERG_ESTEEM_SCORE__2018
0,1,7.0,7.0,7.0,3.0,3.0,1.0,2.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,7.0,7.0,7.0,3.0,3.0,0.0,4.0,3.0,2.0,...,24.0,24.0,24.0,24.0,24.0,24.0,24.0,24.0,24.0,24.0
2,3,7.0,7.0,7.0,3.0,4.0,1.0,2.0,4.0,3.0,...,25.0,25.0,25.0,25.0,25.0,25.0,25.0,25.0,25.0,25.0
3,4,7.0,7.0,7.0,3.0,3.0,0.0,1.0,2.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,7.0,7.0,7.0,3.0,3.0,0.0,2.0,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12681,12682,7.0,7.0,7.0,4.0,4.0,1.0,4.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12682,12683,2.0,2.0,2.0,2.0,3.0,1.0,1.0,2.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12683,12684,7.0,7.0,0.0,2.0,1.0,1.0,2.0,2.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12684,12685,2.0,2.0,9.0,2.0,2.0,1.0,2.0,2.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12685,12686,0.0,0.0,1.0,2.0,2.0,1.0,1.0,2.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
attitudes_long = pd.wide_to_long(attitudes, stubnames = sub_unique_var_name, i=id_list, j='Year', sep='__')

attitudes_long

                                             cat_o_HEALTH-SOC_1  \
ID    SAMPLE_ID SAMPLE_RACE SAMPLE_SEX Year
1     5         3           2          1979                 NaN
                                       1980                 NaN
                                       1981                 NaN
                                       1982                 NaN
                                       1983                 NaN
...                                                         ...
12686 1         3           1          2014                 1.0
                                       2015                 1.0
                                       2016                 1.0
                                       2017                 1.0
                                       2018                 1.0

                                             cat_o_PEARLIN_3  \
ID    SAMPLE_ID SAMPLE_RACE SAMPLE_SEX Year
1     5         3           2          1979              NaN
                                       1980              NaN
                                       1981              NaN
                                       1982              NaN
                                       1983              NaN
...                                                      ...
12686 1         3           1          2014              1.0
                                       2015              1.0
                                       2016              1.0
                                       2017              1.0
                                       2018              1.0

                                             ctn_PEARLIN_SCORE  \
ID    SAMPLE_ID SAMPLE_RACE SAMPLE_SEX Year
1     5         3           2          1979                NaN
                                       1980                NaN
                                       1981                NaN
                                       1982                NaN
                                       1983                NaN
...                                                        ...
12686 1         3           1          2014               25.0
                                       2015               25.0
                                       2016               25.0
                                       2017               25.0
                                       2018               25.0

                                             cat_o_WOMENS-ROLES_000003  \
ID    SAMPLE_ID SAMPLE_RACE SAMPLE_SEX Year
1     5         3           2          1979                        1.0
                                       1980                        1.0
                                       1981                        1.0
                                       1982                        NaN
                                       1983                        NaN
...                                                                ...
12686 1         3           1          2014                        NaN
                                       2015                        NaN
                                       2016                        NaN
                                       2017                        NaN
                                       2018                        NaN

                                             cat_o_WOMENS-ROLES_000001  \
ID    SAMPLE_ID SAMPLE_RACE SAMPLE_SEX Year
1     5         3           2          1979                        2.0
                                       1980                        2.0
                                       1981                        2.0
                                       1982                        NaN
                                       1983                        NaN
...                                                                ...
12686 1         3           1          2014                        1.0
                                       2015                        1.0
                                       2016                        1.0
                                       2017                        1.0
                                       2018                        1.0

                                             ctn_FER-1B  cat_o_PEARLIN_2  \
ID    SAMPLE_ID SAMPLE_RACE SAMPLE_SEX Year
1     5         3           2          1979         3.0              NaN
                                       1980         3.0              NaN
                                       1981         3.0              NaN
                                       1982         NaN              NaN
                                       1983         NaN              NaN
...                                                 ...              ...
12686 1         3           1          2014         2.0              3.0
                                       2015         2.0              3.0
                                       2016         2.0              3.0
                                       2017         2.0              3.0
                                       2018         2.0              3.0

                                             cat_o_PEARLIN_6  cat_o_PEARLIN_7  \
ID    SAMPLE_ID SAMPLE_RACE SAMPLE_SEX Year
1     5         3           2          1979              NaN              NaN
                                       1980              NaN              NaN
                                       1981              NaN              NaN
                                       1982              NaN              NaN
                                       1983              NaN              NaN
...                                                      ...              ...
12686 1         3           1          2014              4.0              1.0
                                       2015              4.0              1.0
                                       2016              4.0              1.0
                                       2017              4.0              1.0
                                       2018              4.0              1.0

                                             cat_d_WOW-4  ...  \
ID    SAMPLE_ID SAMPLE_RACE SAMPLE_SEX Year               ...
1     5         3           2          1979          1.0  ...
                                       1980          1.0  ...
                                       1981          1.0  ...
                                       1982          1.0  ...
                                       1983          1.0  ...
...                                                  ...  ...
12686 1         3           1          2014          1.0  ...
                                       2015          1.0  ...
                                       2016          1.0  ...
                                       2017          1.0  ...
                                       2018          1.0  ...

                                             cat_R_REL-1_COL  \
ID    SAMPLE_ID SAMPLE_RACE SAMPLE_SEX Year
1     5         3           2          1979              7.0
                                       1980              7.0
                                       1981              7.0
                                       1982              7.0
                                       1983              7.0
...                                                      ...
12686 1         3           1          2014              0.0
                                       2015              0.0
                                       2016              0.0
                                       2017              0.0
                                       2018              0.0

                                             cat_o_ROSENBERG_ESTEEM~000006  \
ID    SAMPLE_ID SAMPLE_RACE SAMPLE_SEX Year
1     5         3           2          1979                            NaN
                                       1980                            NaN
                                       1981                            NaN
                                       1982                            NaN
                                       1983                            NaN
...                                                                    ...
12686 1         3           1          2014                            1.0
                                       2015                            1.0
                                       2016                            1.0
                                       2017                            1.0
                                       2018                            1.0

                                             cat_o_ATT-POL-79  ctn_FER-1A  \
ID    SAMPLE_ID SAMPLE_RACE SAMPLE_SEX Year
1     5         3           2          1979               NaN         3.0
                                       1980               NaN         3.0
                                       1981               NaN         3.0
                                       1982               NaN         NaN
                                       1983               NaN         NaN
...                                                       ...         ...
12686 1         3           1          2014               NaN         2.0
                                       2015               NaN         2.0
                                       2016               NaN         2.0
                                       2017               NaN         2.0
                                       2018               NaN         2.0

                                             cat_EXP-OCC  \
ID    SAMPLE_ID SAMPLE_RACE SAMPLE_SEX Year
1     5         3           2          1979          NaN
                                       1980          NaN
                                       1981          NaN
                                       1982          NaN
                                       1983          NaN
...                                                  ...
12686 1         3           1          2014        492.0
                                       2015        492.0
                                       2016        492.0
                                       2017        492.0
                                       2018        492.0

                                             cat_o_ROSENBERG_ESTEEM~000010  \
ID    SAMPLE_ID SAMPLE_RACE SAMPLE_SEX Year
1     5         3           2          1979                            NaN
                                       1980                            NaN
                                       1981                            NaN
                                       1982                            NaN
                                       1983                            NaN
...                                                                    ...
12686 1         3           1          2014                            4.0
                                       2015                            4.0
                                       2016                            4.0
                                       2017                            4.0
                                       2018                            4.0

                                             cat_o_ROSENBERG_ESTEEM~000005  \
ID    SAMPLE_ID SAMPLE_RACE SAMPLE_SEX Year
1     5         3           2          1979                            NaN
                                       1980                            NaN
                                       1981                            NaN
                                       1982                            NaN
                                       1983                            NaN
...                                                                    ...
12686 1         3           1          2014                            4.0
                                       2015                            4.0
                                       2016                            4.0
                                       2017                            4.0
                                       2018                            4.0

                                             cat_o_WOMENS-ROLES_000007  \
ID    SAMPLE_ID SAMPLE_RACE SAMPLE_SEX Year
1     5         3           2          1979                        1.0
                                       1980                        1.0
                                       1981                        1.0
                                       1982                        NaN
                                       1983                        NaN
...                                                                ...
12686 1         3           1          2014                        4.0
                                       2015                        4.0
                                       2016                        4.0
                                       2017                        4.0
                                       2018                        4.0

                                             cat_o_ROSENBERG_ESTEEM~000007  \
ID    SAMPLE_ID SAMPLE_RACE SAMPLE_SEX Year
1     5         3           2          1979                            NaN
                                       1980                            NaN
                                       1981                            NaN
                                       1982                            NaN
                                       1983                            NaN
...                                                                    ...
12686 1         3           1          2014                            1.0
                                       2015                            1.0
                                       2016                            1.0
                                       2017                            1.0
                                       2018                            1.0

                                             cat_R_REL-1
ID    SAMPLE_ID SAMPLE_RACE SAMPLE_SEX Year
1     5         3           2          1979          7.0
                                       1980          7.0
                                       1981          7.0
                                       1982          7.0
                                       1983          7.0
...                                                  ...
12686 1         3           1          2014          NaN
                                       2015          NaN
                                       2016          NaN
                                       2017          NaN
                                       2018          NaN

[507440 rows x 38 columns]

In [62]:
#Saving 
attitudes = attitudes
attitudes_wide_path = path_main_attitudes + "Attitudes_wide.csv"
with open(attitudes_wide_path , 'w', encoding = 'utf-8-sig') as f:
  attitudes.to_csv(f)

In [63]:
attitudes_long_path = path_main_attitudes + "Attitudes_long.csv"
with open(attitudes_long_path , 'w', encoding = 'utf-8-sig') as f:
  attitudes_long.to_csv(f)